//! Bucket-2 repository-envelope policy and rendered fleet tasks.
//!
//! This module is deliberately text-oriented. The consumer repository owns the
//! bodies of its existing mise tasks and repolint sections; the generator owns
//! only the namespaced fleet task block and the marked AGENTS block.

use crate::RepositoryClass;
use crate::model::{CensusMetadata, RepositoryTier};

/// Stable `.ignore` content rendered for every consumer.
pub const IGNORE_FILE: &str = r#"# Generated by velnor-actions-generator. DO NOT EDIT.
# Local build output, dependency caches, and fleet run artifacts.
target/
node_modules/
.venv/
__pycache__/
.DS_Store
.velnor-compare/
.last-publish
YOLO_*.md
dist/
build/
*.lock
!Cargo.lock
!mise.lock
"#;

/// Generator-owned markers in AGENTS.md.
const AGENTS_BEGIN: &str = "<!-- VELNOR-ACTIONS:BEGIN -->";
const AGENTS_END: &str = "<!-- VELNOR-ACTIONS:END -->";

/// The exact generated fleet task names. Existing task names are never replaced.
pub const FLEET_TASK_NAMES: [&str; 3] = ["fleet:check", "fleet:map", "fleet:census"];

/// Weekly audit owned by the canonical generator repository.
pub const FLEET_AUDIT_WORKFLOW: &str = r#"# Generated by velnor-actions-generator. DO NOT EDIT.
name: fleet-audit

on:
  schedule:
    - cron: "17 4 * * 1"
  workflow_dispatch:

permissions:
  {}

jobs:
  audit:
    permissions:
      contents: write
    runs-on: ubuntu-26.04
    timeout-minutes: 45
    steps:
      - name: Check out fleet census
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up mise
        uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4.2.4
      - name: Install locked audit tools
        run: mise install --locked
      - name: Shallow-clone census and run the common audit
        env:
          GH_TOKEN: ${{ github.token }}
        run: cargo run --locked -p velnor-actions-generator -- fleet-audit --root . --write-deferred
      - name: Commit generated deferred aggregate
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          if git diff --quiet -- fleet/deferred.toml; then
            echo "fleet/deferred.toml is current"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add fleet/deferred.toml
          git commit -s -m "chore(fleet): refresh deferred aggregate"
          git -c http.extraheader="AUTHORIZATION: bearer ${GH_TOKEN}" push origin HEAD:main
"#;

/// Render the invariant block for an AGENTS.md file.
#[must_use]
pub fn agents_block(has_map: bool, tier: RepositoryTier) -> String {
    let map = if has_map {
        "Repository map: README → ## Repository map"
    } else {
        return format!(
            "{AGENTS_BEGIN}\nRepository map: none — {} tier\nDeferred work: repolint.toml [[deferred.item]]\n{AGENTS_END}",
            tier.token()
        );
    };
    format!("{AGENTS_BEGIN}\n{map}\nDeferred work: repolint.toml [[deferred.item]]\n{AGENTS_END}")
}

/// Replace the generator-owned AGENTS block while preserving all repo prose.
pub fn render_agents(existing: &str, metadata: &CensusMetadata) -> String {
    let block = agents_block(existing.contains("## Repository map"), metadata.tier);
    if let (Some(begin), Some(end)) = (existing.find(AGENTS_BEGIN), existing.find(AGENTS_END))
        && begin < end
    {
        let end = end + AGENTS_END.len();
        let mut rendered = String::with_capacity(existing.len() + block.len());
        rendered.push_str(&existing[..begin]);
        rendered.push_str(&block);
        rendered.push_str(&existing[end..]);
        return normalize_newline(&rendered);
    }
    let mut rendered = existing.trim_end().to_owned();
    if !rendered.is_empty() {
        rendered.push_str("\n\n");
    }
    rendered.push_str(&block);
    rendered.push('\n');
    rendered
}

/// Render the per-class alint policy. Findings are warnings until the repo
/// adopts repolint `[repo]`; `fleet:check` promotes them with `--fail-on-warning`.
#[must_use]
pub fn alint_config(class: RepositoryClass) -> String {
    let class = class.code();
    format!(
        r#"# Generated by velnor-actions-generator for the {class} class. DO NOT EDIT.
version: 1

facts:
  - id: has_docker
    any_file_exists: [Dockerfile, "*/Dockerfile", "Dockerfile.*"]

rules:
  - id: taxonomy.forbidden-zones
    kind: dir_absent
    paths: [native, frontend, "backend*", lib, libs, proto, cli, xtask, common, shared, utils]
    level: warning
    message: "Banned taxonomy zone; register legacy layout in repolint.toml before migration."

  - id: containment.no-parent-escape
    kind: file_content_forbidden
    paths:
      include: ["**/*.toml", "**/*.yml", "**/*.yaml", "**/*.json", "**/*.swift", "**/*.gradle", "**/*.gradle.kts"]
      exclude: [".github/workflows/**"]
    pattern: '(?:\.\./){{2,}}'
    level: warning
    message: "Committed build/config paths must not escape the repository."

  - id: containment.no-absolute-home
    kind: file_content_forbidden
    paths:
      include: ["**/*.toml", "**/*.yml", "**/*.yaml", "**/*.json", "**/*.swift", "**/*.sh", "**/*.bash"]
      exclude: [".github/workflows/**"]
    pattern: '/(?:Users|home)/'
    level: warning
    message: "Committed build files must not contain absolute home paths."

  - id: ignore.present
    kind: file_content_matches
    paths: .ignore
    pattern: '(?m)^(?:target/|node_modules/|\.DS_Store)'
    level: warning
    message: ".ignore must cover build output, dependencies, and OS junk."

  - id: mise.root-toml
    kind: file_exists
    paths: [mise.toml, mise.lock]
    root_only: true
    level: warning
    message: "Root mise.toml and committed mise.lock are required."

  - id: mise.verbs
    kind: file_content_matches
    paths: mise.toml
    pattern: '(?m)^\[tasks\.(?:fmt|fmt-fix|lint|test|check|ci)(?:\]|\")'
    level: warning
    message: "The root mise interface must expose the standard verbs."

  - id: docker.context-ignore
    when: facts.has_docker
    kind: every_matching_has
    select: ["**/Dockerfile", "**/Dockerfile.*"]
    require:
      - kind: file_exists
        paths: .dockerignore
        level: warning
    level: warning
    message: "Every Docker build context needs a committed .dockerignore."

  - id: docker.build-task-is-scan
    when: facts.has_docker
    kind: file_content_matches
    paths: mise.toml
    pattern: '(?im)(docker build|build-all).*(scan|trivy|syft)'
    level: warning
    message: "Docker build tasks must derive from a scan-backed image manifest."

  - id: generated.drift
    kind: file_exists
    paths: .github/workflows/ci.yml
    level: warning
    message: "The rendered consumer workflow must exist before drift can be checked."

  - id: docs.no-run-artifacts
    kind: git_no_denied_paths
    denied: [".velnor-compare/**", ".last-publish", "YOLO_*.md"]
    level: warning
    message: "Fleet run artifacts must not be committed."
"#
    )
}

/// Render the generator-owned task block for one repository class.
#[must_use]
pub fn fleet_tasks(metadata: &CensusMetadata, class: RepositoryClass) -> String {
    let activation = "test -f repolint.toml && grep -q '^\\[repo\\]$' repolint.toml".to_owned();
    let census = format!(
        "printf 'repository class: {}\\ntier: {}\\nkind: {}\\nvisibility: {}\\nresearch: {}\\nfirst_seen: {}\\n'",
        class.code(),
        metadata.tier.token(),
        metadata.kind.token(),
        metadata.visibility.token(),
        metadata.research,
        metadata.first_seen
    );
    format!(
        r#"[tasks."fleet:check"]
description = "Run the fleet structure, repository-shape, and workflow security gates"
run = [
  "repolint check",
  "if {activation}; then alint check --fail-on-warning; else alint check; fi",
  "zizmor .github/workflows",
]

[tasks."fleet:map"]
description = "Regenerate the linter-owned README repository map"
run = "repolint map --write"

[tasks."fleet:census"]
description = "Print this repository's authoritative fleet census row"
run = {census:?}
"#
    )
}

/// Render the generator-owned `[repo]` cache. Other repolint sections are
/// intentionally not represented here and therefore cannot be overwritten.
#[must_use]
pub fn repolint_repo_table(metadata: &CensusMetadata) -> String {
    format!(
        "[repo]\ntier = \"{}\"\nkind = \"{}\"\nvisibility = \"{}\"\nresearch = {}\n",
        metadata.tier.token().to_ascii_lowercase(),
        metadata.kind.token().to_ascii_lowercase(),
        metadata.visibility.token(),
        metadata.research
    )
}

/// Update only `[repo]` in an existing repolint config.
pub fn render_repolint(existing: &str, metadata: &CensusMetadata) -> String {
    let table = repolint_repo_table(metadata);
    let mut output = String::new();
    let mut in_repo = false;
    let mut replaced = false;
    for line in existing.lines() {
        let trimmed = line.trim();
        if trimmed == "[repo]" {
            if !replaced {
                output.push_str(&table);
                replaced = true;
            }
            in_repo = true;
            continue;
        }
        if in_repo && trimmed.starts_with('[') && trimmed.ends_with(']') {
            in_repo = false;
        }
        if !in_repo {
            output.push_str(line);
            output.push('\n');
        }
    }
    if !replaced {
        let mut prefix = table;
        prefix.push('\n');
        prefix.push_str(existing);
        return normalize_newline(&prefix);
    }
    normalize_newline(&output)
}

/// Render exact census output for the root `fleet:census` task.
#[must_use]
pub fn census_output(manifest: &crate::model::FleetManifest) -> String {
    let counts = manifest.census_counts();
    let format_counts = |values: &std::collections::BTreeMap<&'static str, usize>| {
        values
            .iter()
            .map(|(name, count)| format!("{name}={count}"))
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!(
        "census: total={} tiers=[{}] kinds=[{}] visibility=[{}] research={}",
        counts.total,
        format_counts(&counts.tiers),
        format_counts(&counts.kinds),
        format_counts(&counts.visibilities),
        counts.research
    )
}

/// Add or replace only the generator-owned `fleet:*` task tables.
pub fn render_mise_tasks(existing: &str, tasks: &str) -> String {
    let generated = FLEET_TASK_NAMES
        .iter()
        .map(|name| format!("[tasks.\"{name}\"]"))
        .collect::<std::collections::BTreeSet<_>>();
    let mut output = String::new();
    let mut skipping = false;
    for line in existing.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') && trimmed.ends_with(']') {
            skipping = generated.contains(trimmed);
        }
        if !skipping {
            output.push_str(line);
            output.push('\n');
        }
    }
    if !output.ends_with("\n\n") {
        output.push('\n');
    }
    output.push_str(tasks.trim_start());
    if !output.ends_with('\n') {
        output.push('\n');
    }
    output
}

fn normalize_newline(value: &str) -> String {
    let mut output = value.replace("\r\n", "\n").replace('\r', "\n");
    if !output.ends_with('\n') {
        output.push('\n');
    }
    output
}
