//! Deterministic workflow rendering.
//!
//! Every rendered file is byte-stable: Unix (LF) line endings, UTF-8, a single
//! final newline, no trailing whitespace, and content that depends only on
//! declared data — never on timestamps, host paths, repository slug, or
//! environment. The two consumer-facing release tokens (`@FLEET_SHA@` and
//! `@CALVER@`) are the only non-executable placeholders; `render_consumer`
//! replaces them atomically.

use crate::RepositoryClass;
use crate::cache::{CacheContract, CacheDeclaration};
use crate::model::{ClassContract, Gate, Lane, OWNERS};
use sha2::{Digest, Sha256};

/// The canonical fleet owner. Callable workflows pin their internal composite
/// closure to this owner at the immutable block SHA; mirrors carry the identical
/// bytes.
pub const CANONICAL_OWNER: &str = "tailrocks";
/// The fleet repository name shared across all three owner-local mirrors.
pub const ACTIONS_REPO: &str = "velnor-actions";

/// The `@FLEET_SHA@` release-pin placeholder (the consumer's immutable ref).
pub const FLEET_SHA_PLACEHOLDER: &str = "@FLEET_SHA@";
/// The `@CALVER@` release-version-comment placeholder.
pub const CALVER_PLACEHOLDER: &str = "@CALVER@";

/// Pinned checkout action (full 40-hex SHA) and its version comment.
const CHECKOUT_REF: &str = "3d3c42e5aac5ba805825da76410c181273ba90b1";
const CHECKOUT_VERSION: &str = "v7.0.1";
/// Pinned mise setup action (full 40-hex SHA) and its version comment.
const MISE_ACTION_REF: &str = "7e36c90d9ab29c415a2384db3006f3ec8a8cc654";
const MISE_ACTION_VERSION: &str = "v4.2.4";
/// Pinned GitHub cache action.
const CACHE_ACTION_REF: &str = "55cc8345863c7cc4c66a329aec7e433d2d1c52a9";
const CACHE_ACTION_VERSION: &str = "v6.1.0";
const UPLOAD_ARTIFACT_REF: &str = "043fb46d1a93c77aae656e7c1c64a875d1fc6a0a";
const UPLOAD_ARTIFACT_VERSION: &str = "v7.0.1";
const DOWNLOAD_ARTIFACT_REF: &str = "3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c";
const DOWNLOAD_ARTIFACT_VERSION: &str = "v8.0.1";

/// The generated workflow file name for a class: `ci-<class>.yml`.
#[must_use]
pub fn callable_file_name(class: RepositoryClass) -> String {
    format!("ci-{}.yml", class.code())
}

struct Builder {
    lines: Vec<String>,
}

impl Builder {
    fn new() -> Builder {
        Builder { lines: Vec::new() }
    }

    fn line(&mut self, indent: usize, text: &str) {
        if text.is_empty() {
            self.lines.push(String::new());
        } else {
            self.lines.push(format!("{}{}", " ".repeat(indent), text));
        }
    }

    fn blank(&mut self) {
        self.lines.push(String::new());
    }

    /// Emit a `run: |` block: the key at `indent`, script body at `indent + 2`.
    fn run_block(&mut self, indent: usize, script: &str) {
        self.line(indent, "run: |");
        for l in script.lines() {
            if l.is_empty() {
                self.lines.push(String::new());
            } else {
                self.lines.push(format!("{}{}", " ".repeat(indent + 2), l));
            }
        }
    }

    fn finish(self) -> String {
        let mut out = self.lines.join("\n");
        out.push('\n');
        out
    }
}

/// Render the committed consumer template for a class. The three owner-local
/// reusable-workflow calls share the same anchored `@FLEET_SHA@ # @CALVER@`
/// release pin; `render_consumer` replaces both tokens together at release time.
#[must_use]
pub fn consumer_template(class: RepositoryClass) -> String {
    let file = callable_file_name(class);
    let mut b = Builder::new();
    b.line(0, "# Generated by velnor-actions-generator. DO NOT EDIT.");
    b.line(0, "#");
    b.line(
        0,
        &format!(
            "# Canonical consumer template for the {} class. Every {} repository renders",
            class.code(),
            class.code()
        ),
    );
    b.line(
        0,
        "# this same file (byte-identical within the class) as .github/workflows/ci.yml.",
    );
    b.line(
        0,
        "# The three owner-local reusable-workflow calls are selected solely by",
    );
    b.line(
        0,
        "# github.repository_owner: exactly one runs and the other two skip. The shared",
    );
    b.line(
        0,
        "# release SHA pin and CalVer version comment are identical across all three",
    );
    b.line(
        0,
        "# calls and are replaced together at release time by render-consumer.",
    );
    b.line(0, "name: CI");
    b.line(0, "run-name: ${{ inputs.recovery_proof_id != '' && format('CI recovery {0}', inputs.recovery_proof_id) || inputs.benchmark_campaign != '' && format('CI benchmark {0}/{1}', inputs.benchmark_campaign, inputs.benchmark_wave) || inputs.cache_proof_id != '' && format('CI cache proof {0}', inputs.cache_proof_id) || 'CI' }}");
    b.blank();
    b.line(0, "on:");
    b.line(2, "pull_request:");
    b.line(2, "push:");
    b.line(2, "merge_group:");
    b.line(2, "workflow_dispatch:");
    b.line(4, "inputs:");
    b.line(6, "lane:");
    b.line(8, "description: \"Optional CI lane: github, velnor, or both. Empty uses organization default.\"");
    b.line(8, "required: false");
    b.line(8, "type: string");
    b.line(8, "default: \"\"");
    consumer_auxiliary_inputs(&mut b);
    b.blank();
    b.line(0, "permissions:");
    b.line(2, "actions: read");
    b.line(2, "contents: read");
    b.blank();
    b.line(0, "concurrency:");
    b.line(2, "group: ${{ inputs.benchmark_campaign != '' && format('{0}-{1}-{2}', github.workflow, inputs.benchmark_campaign, inputs.benchmark_wave) || format('{0}-{1}', github.workflow, github.ref) }}");
    b.line(
        2,
        "cancel-in-progress: ${{ inputs.benchmark_campaign == '' }}",
    );
    b.blank();
    b.line(0, "jobs:");

    for owner in OWNERS {
        b.line(2, &format!("{owner}:"));
        b.line(4, &format!("name: {owner}"));
        b.line(
            4,
            &format!("if: ${{{{ github.repository_owner == '{owner}' }}}}"),
        );
        b.line(4, "permissions:");
        b.line(6, "contents: read");
        b.line(
            4,
            &format!(
                "uses: {owner}/{ACTIONS_REPO}/.github/workflows/{file}@{FLEET_SHA_PLACEHOLDER} # {CALVER_PLACEHOLDER}"
            ),
        );
        b.line(4, "with:");
        b.line(
            6,
            "lane: ${{ (github.event_name == 'workflow_dispatch' && inputs.lane != '' && inputs.lane) || (github.repository_owner == 'jackin-project' && 'github') || ((github.repository_owner == 'tailrocks' || github.repository_owner == 'ChainArgos') && 'velnor') || 'invalid' }}",
        );
        for input in AUXILIARY_INPUTS {
            b.line(6, &format!("{input}: ${{{{ inputs.{input} || '' }}}}"));
        }
        b.blank();
    }

    // ci-required aggregator: fail-closed positive truth table.
    b.line(2, "ci-required:");
    b.line(4, "name: ci-required");
    b.line(4, "needs:");
    for owner in OWNERS {
        b.line(6, &format!("- {owner}"));
    }
    b.line(4, "if: ${{ always() }}");
    b.line(4, "runs-on: ubuntu-latest");
    b.line(4, "timeout-minutes: 10");
    b.line(4, "permissions:");
    b.line(6, "contents: read");
    b.line(4, "steps:");
    b.line(6, "- name: Enforce fleet contract");
    b.line(8, "env:");
    b.line(10, "OWNER: ${{ github.repository_owner }}");
    b.line(
        10,
        "JACKIN_PROJECT_RESULT: ${{ needs.jackin-project.result }}",
    );
    b.line(
        10,
        "JACKIN_PROJECT_CONTRACT: ${{ needs.jackin-project.outputs.contract }}",
    );
    b.line(10, "TAILROCKS_RESULT: ${{ needs.tailrocks.result }}");
    b.line(
        10,
        "TAILROCKS_CONTRACT: ${{ needs.tailrocks.outputs.contract }}",
    );
    b.line(10, "CHAINARGOS_RESULT: ${{ needs.ChainArgos.result }}");
    b.line(
        10,
        "CHAINARGOS_CONTRACT: ${{ needs.ChainArgos.outputs.contract }}",
    );
    b.line(8, "shell: bash");
    b.run_block(8, CI_REQUIRED_SCRIPT);

    b.finish()
}

/// Render the owner-local callable workflow for a class, pinning its internal
/// composite closure to `block_sha` (a validated 40-hex SHA).
#[must_use]
pub fn callable_workflow(
    contract: &ClassContract,
    caches: &CacheContract,
    block_sha: &str,
) -> String {
    let class = contract.class;
    let run_gate = format!("{CANONICAL_OWNER}/{ACTIONS_REPO}/actions/run-gate@{block_sha}");
    let aggregate = format!("{CANONICAL_OWNER}/{ACTIONS_REPO}/actions/aggregate@{block_sha}");

    let mut b = Builder::new();
    b.line(0, "# Generated by velnor-actions-generator. DO NOT EDIT.");
    b.line(
        0,
        &format!(
            "# Cache declaration SHA-256: {}",
            caches.declaration_sha256()
        ),
    );
    b.line(0, "#");
    b.line(
        0,
        &format!(
            "# Owner-local reusable CI workflow for the {} class. Consumers call their own",
            class.code()
        ),
    );
    b.line(
        0,
        "# organization's mirror of this file. It owns the lane jobs, runs identical gate",
    );
    b.line(
        0,
        "# commands on either lane through the run-gate building block, and emits the lane",
    );
    b.line(
        0,
        "# contract only after every applicable gate genuinely succeeds. It inherits no",
    );
    b.line(
        0,
        "# secrets and no environment. The internal composite closure is pinned to the",
    );
    b.line(0, "# immutable block SHA recorded in fleet/block-sha.");
    b.line(0, &format!("name: ci-{}", class.code()));
    b.blank();
    b.line(0, "on:");
    b.line(2, "workflow_call:");
    b.line(4, "inputs:");
    b.line(6, "lane:");
    b.line(
        8,
        "description: \"CI lane: github, velnor, or both; empty derives from owner.\"",
    );
    b.line(8, "required: false");
    b.line(8, "type: string");
    b.line(8, "default: \"\"");
    callable_auxiliary_inputs(&mut b);
    b.line(4, "outputs:");
    b.line(6, "contract:");
    b.line(
        8,
        "description: \"'success' only when every selected lane passed its applicable gates.\"",
    );
    b.line(8, "value: ${{ jobs.contract.outputs.contract }}");
    b.line(6, "correlation:");
    b.line(
        8,
        "description: \"Authenticated recovery, benchmark, or cache-proof correlation.\"",
    );
    b.line(8, "value: ${{ jobs.validate-request.outputs.correlation }}");
    b.blank();
    b.line(0, "permissions:");
    b.line(2, "actions: read");
    b.line(2, "contents: read");
    b.blank();
    b.line(0, "jobs:");
    b.line(2, "validate-request:");
    b.line(4, "name: validate request");
    b.line(4, "runs-on: ubuntu-latest");
    b.line(4, "timeout-minutes: 5");
    b.line(4, "permissions:");
    b.line(6, "contents: read");
    b.line(4, "outputs:");
    b.line(6, "correlation: ${{ steps.validate.outputs.correlation }}");
    b.line(4, "steps:");
    b.line(6, "- name: Authenticate optional operation");
    b.line(8, "id: validate");
    b.line(8, "shell: bash");
    b.line(8, "env:");
    for input in AUXILIARY_INPUTS {
        b.line(
            10,
            &format!("{}: ${{{{ inputs.{input} }}}}", input.to_ascii_uppercase()),
        );
    }
    b.line(10, "EVENT_NAME: ${{ github.event_name }}");
    b.line(10, "REF_TYPE: ${{ github.ref_type }}");
    b.line(10, "REF_PROTECTED: ${{ github.ref_protected }}");
    b.line(10, "HEAD_SHA: ${{ github.sha }}");
    b.line(10, "WORKFLOW_SHA: ${{ github.workflow_sha }}");
    b.line(10, "GH_TOKEN: ${{ github.token }}");
    b.line(10, "REPOSITORY: ${{ github.repository }}");
    let cache_ids = caches
        .declarations()
        .iter()
        .filter(|cache| cache.class == class)
        .map(|cache| cache.id.as_str())
        .collect::<Vec<_>>()
        .join(",");
    b.line(10, &format!("DECLARED_CACHE_IDS: {cache_ids}"));
    b.run_block(8, VALIDATE_REQUEST_SCRIPT);
    b.blank();

    // Velnor lane.
    b.line(2, "velnor-lane:");
    b.line(4, "name: velnor lane");
    b.line(4, "needs: validate-request");
    b.line(
        4,
        "if: ${{ inputs.benchmark_campaign == '' && inputs.cache_proof_id == '' && (inputs.lane == 'velnor' || inputs.lane == 'both' || (inputs.lane == '' && (github.repository_owner == 'tailrocks' || github.repository_owner == 'ChainArgos'))) }}",
    );
    b.line(
        4,
        "# Public unmerged-code events (pull_request, merge_group) route the Velnor lane",
    );
    b.line(
        4,
        "# to GitHub-hosted execution until a live-proven lower-trust Velnor pool exists.",
    );
    b.line(4, "# This is explicit policy routing, not silent failover.");
    b.line(
        4,
        "runs-on: ${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && 'ubuntu-latest' || 'velnor-trusted' }}",
    );
    b.line(4, "timeout-minutes: 30");
    b.line(4, "outputs:");
    b.line(6, "contract: ${{ steps.aggregate.outputs.contract }}");
    b.line(4, "steps:");
    b.line(6, "- name: Report Velnor lane routing policy");
    b.line(
        8,
        "if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}",
    );
    b.line(8, "shell: bash");
    b.run_block(
        8,
        "echo 'policy: public unmerged-code routes the Velnor lane to GitHub-hosted execution'",
    );
    lane_steps(
        &mut b,
        contract,
        caches,
        Lane::Velnor,
        &run_gate,
        &aggregate,
    );
    b.blank();

    // GitHub-hosted lane.
    b.line(2, "github-lane:");
    b.line(4, "name: github lane");
    b.line(4, "needs: validate-request");
    b.line(
        4,
        "if: ${{ inputs.benchmark_campaign == '' && inputs.cache_proof_id == '' && (inputs.lane == 'github' || inputs.lane == 'both' || (inputs.lane == '' && github.repository_owner == 'jackin-project')) }}",
    );
    b.line(4, "runs-on: ubuntu-latest");
    b.line(4, "timeout-minutes: 30");
    b.line(4, "outputs:");
    b.line(6, "contract: ${{ steps.aggregate.outputs.contract }}");
    b.line(4, "steps:");
    lane_steps(
        &mut b,
        contract,
        caches,
        Lane::GitHub,
        &run_gate,
        &aggregate,
    );
    b.blank();

    if contract.platform_only {
        b.line(2, "platform-lane:");
        b.line(4, "name: GitHub platform lane");
        b.line(4, "needs: validate-request");
        b.line(4, "runs-on: macos-latest");
        b.line(4, "timeout-minutes: 30");
        b.line(4, "outputs:");
        b.line(6, "contract: ${{ steps.aggregate.outputs.contract }}");
        b.line(4, "steps:");
        b.line(6, "- name: Check out repository");
        b.line(
            8,
            &format!("uses: actions/checkout@{CHECKOUT_REF} # {CHECKOUT_VERSION}"),
        );
        b.line(6, "- name: Set up mise toolchain");
        b.line(
            8,
            &format!("uses: jdx/mise-action@{MISE_ACTION_REF} # {MISE_ACTION_VERSION}"),
        );
        for gate in &contract.gates {
            if gate.applicability == crate::model::Applicability::Github {
                gate_step(&mut b, gate, &run_gate);
            }
        }
        b.line(6, "- name: Emit platform contract");
        b.line(8, "id: aggregate");
        b.line(8, &format!("uses: {aggregate}"));
        b.blank();
    }

    render_cache_proof_jobs(&mut b, contract, caches, block_sha, &run_gate, &aggregate);

    // Lane-verdict aggregator: fail-closed positive per-lane truth table.
    b.line(2, "contract:");
    b.line(4, "name: contract");
    b.line(4, "needs:");
    b.line(6, "- velnor-lane");
    b.line(6, "- github-lane");
    if contract.platform_only {
        b.line(6, "- platform-lane");
    }
    b.line(6, "- cache-proof-contract");
    b.line(4, "if: ${{ always() }}");
    b.line(4, "runs-on: ubuntu-latest");
    b.line(4, "timeout-minutes: 10");
    b.line(4, "outputs:");
    b.line(6, "contract: ${{ steps.verdict.outputs.contract }}");
    b.line(4, "steps:");
    b.line(6, "- name: Aggregate lane verdict");
    b.line(8, "id: verdict");
    b.line(8, "env:");
    b.line(10, "LANE: ${{ inputs.lane != '' && inputs.lane || (github.repository_owner == 'jackin-project' && 'github') || ((github.repository_owner == 'tailrocks' || github.repository_owner == 'ChainArgos') && 'velnor') || 'invalid' }}");
    b.line(10, "VELNOR_RESULT: ${{ needs.velnor-lane.result }}");
    b.line(
        10,
        "VELNOR_CONTRACT: ${{ needs.velnor-lane.outputs.contract }}",
    );
    b.line(10, "GITHUB_RESULT: ${{ needs.github-lane.result }}");
    b.line(
        10,
        "GITHUB_CONTRACT: ${{ needs.github-lane.outputs.contract }}",
    );
    b.line(
        10,
        &format!("PLATFORM_REQUIRED: {}", contract.platform_only),
    );
    if contract.platform_only {
        b.line(10, "PLATFORM_RESULT: ${{ needs.platform-lane.result }}");
        b.line(
            10,
            "PLATFORM_CONTRACT: ${{ needs.platform-lane.outputs.contract }}",
        );
    } else {
        b.line(10, "PLATFORM_RESULT: skipped");
        b.line(10, "PLATFORM_CONTRACT: \"\"");
    }
    b.line(10, "OPERATION: ${{ inputs.benchmark_campaign != '' && 'benchmark' || inputs.cache_proof_id != '' && 'cache-proof' || 'ordinary' }}");
    b.line(
        10,
        "CACHE_PROOF_RESULT: ${{ needs.cache-proof-contract.result }}",
    );
    b.line(
        10,
        "CACHE_PROOF_CONTRACT: ${{ needs.cache-proof-contract.outputs.contract }}",
    );
    b.line(8, "shell: bash");
    b.run_block(8, CONTRACT_VERDICT_SCRIPT);

    b.finish()
}

const AUXILIARY_INPUTS: [&str; 11] = [
    "recovery_proof_id",
    "benchmark_campaign",
    "benchmark_generation",
    "benchmark_cache_id",
    "benchmark_cache_mode",
    "benchmark_fanout",
    "benchmark_wave",
    "benchmark_reservation",
    "cache_proof_id",
    "cache_generation",
    "cache_temperature",
];

fn consumer_auxiliary_inputs(b: &mut Builder) {
    for (name, description) in [
        (
            "recovery_proof_id",
            "Authenticated recovery operation correlation.",
        ),
        (
            "benchmark_campaign",
            "Authenticated benchmark campaign correlation.",
        ),
        ("benchmark_generation", "Benchmark schema generation."),
        ("benchmark_cache_id", "One declared cache identity."),
        ("benchmark_cache_mode", "normal, enabled, or disabled."),
        ("benchmark_fanout", "One or eight coordinated jobs."),
        ("benchmark_wave", "Benchmark wave correlation."),
        ("benchmark_reservation", "Velnor reservation correlation."),
        ("cache_proof_id", "Authenticated cache proof correlation."),
        ("cache_generation", "Cache schema generation 1 or 2."),
        ("cache_temperature", "cold or warm cache truth."),
    ] {
        b.line(6, &format!("{name}:"));
        b.line(8, &format!("description: \"{description}\""));
        b.line(8, "required: false");
        b.line(8, "type: string");
        b.line(8, "default: \"\"");
    }
}

fn callable_auxiliary_inputs(b: &mut Builder) {
    for name in AUXILIARY_INPUTS {
        b.line(6, &format!("{name}:"));
        b.line(8, "required: false");
        b.line(8, "type: string");
        b.line(8, "default: \"\"");
    }
}

fn render_cache_proof_jobs(
    b: &mut Builder,
    contract: &ClassContract,
    caches: &CacheContract,
    block_sha: &str,
    run_gate: &str,
    aggregate: &str,
) {
    let declarations = caches
        .declarations()
        .iter()
        .filter(|cache| cache.class == contract.class)
        .collect::<Vec<_>>();
    for (job, runner, lane) in [
        ("github_restore", "ubuntu-latest", "github"),
        ("velnor_restore", "${{ 'velnor-trusted' }}", "velnor"),
    ] {
        b.line(2, &format!("{job}:"));
        b.line(4, &format!("name: {lane} restore proof"));
        b.line(4, "needs: validate-request");
        b.line(
            4,
            "if: ${{ inputs.benchmark_campaign != '' || inputs.cache_proof_id != '' }}",
        );
        b.line(4, &format!("runs-on: {runner}"));
        b.line(4, "timeout-minutes: 30");
        b.line(4, "permissions:");
        b.line(6, "contents: read");
        b.line(4, "steps:");
        b.line(6, "- name: Check out repository");
        b.line(
            8,
            &format!("uses: actions/checkout@{CHECKOUT_REF} # {CHECKOUT_VERSION}"),
        );
        for cache in &declarations {
            let id = cache.id.as_str();
            let selected = format!(
                "${{{{ inputs.cache_proof_id != '' || inputs.benchmark_cache_id == '{id}' }}}}"
            );
            if lane == "velnor" {
                b.line(6, &format!("- name: Capture {id} proof authority"));
                b.line(8, &format!("id: proof-authority-{id}"));
                b.line(8, &format!("if: {selected}"));
                b.line(8, "shell: bash");
                b.line(8, "env:");
                b.line(
                    10,
                    &format!(
                        "CACHE_ENV_PREFIX: {}",
                        id.replace('-', "_").to_ascii_uppercase()
                    ),
                );
                b.run_block(8, VELNOR_AUTHORITY_CAPTURE_SCRIPT);
                b.line(6, &format!("- name: Validate {id} proof authority"));
                b.line(8, &format!("if: {selected}"));
                b.line(
                    8,
                    &format!(
                        "uses: {CANONICAL_OWNER}/{ACTIONS_REPO}/actions/cache-contract@{block_sha}"
                    ),
                );
                b.line(8, "with:");
                b.line(10, "schema-version: 1");
                b.line(10, &format!("declaration-sha256: ${{{{ steps.proof-authority-{id}.outputs.declaration_sha256 }}}}"));
                b.line(
                    10,
                    &format!(
                        "expected-declaration-sha256: {}",
                        caches.declaration_sha256()
                    ),
                );
                b.line(
                    10,
                    &format!("cache-id: ${{{{ steps.proof-authority-{id}.outputs.cache_id }}}}"),
                );
                b.line(10, &format!("expected-cache-id: {id}"));
                b.line(
                    10,
                    &format!("scope: ${{{{ steps.proof-authority-{id}.outputs.scope }}}}"),
                );
                b.line(10, "expected-scope: trusted");
                b.line(
                    10,
                    &format!("cache-owner: ${{{{ steps.proof-authority-{id}.outputs.owner }}}}"),
                );
                b.line(10, "expected-cache-owner: ${{ github.repository }}");
                b.line(10, &format!("reservation-id: ${{{{ steps.proof-authority-{id}.outputs.reservation_id }}}}"));
                b.line(10, "expected-reservation-id: ${{ inputs.benchmark_reservation != '' && inputs.benchmark_reservation || inputs.cache_proof_id }}");
                b.line(10, &format!("required-peak-bytes: {}", cache.peak_bytes));
                b.line(10, &format!("quota-reserved-bytes: ${{{{ steps.proof-authority-{id}.outputs.reserved_bytes }}}}"));
                b.line(10, &format!("attributed-bytes: ${{{{ steps.proof-authority-{id}.outputs.attributed_bytes }}}}"));
                b.line(
                    10,
                    &format!(
                        "cleanup-state: ${{{{ steps.proof-authority-{id}.outputs.cleanup_state }}}}"
                    ),
                );
                b.line(10, &format!("materialization-id: ${{{{ steps.proof-authority-{id}.outputs.materialization_id }}}}"));
                b.line(
                    10,
                    &format!("expected-materialization-id: ${{{{ github.run_id }}}}-{job}-{id}"),
                );
            }
            b.line(6, &format!("- name: Clean {id} restore destination"));
            b.line(8, &format!("if: {selected}"));
            b.line(8, "shell: bash");
            b.run_block(8, &clean_cache_script(cache));
            b.line(6, &format!("- name: Restore {id} without saving"));
            b.line(8, &format!("id: restore-{id}"));
            b.line(8, &format!("if: ${{{{ (inputs.cache_proof_id != '' || inputs.benchmark_cache_id == '{id}') && (inputs.cache_proof_id == '' || inputs.cache_temperature != 'cold') }}}}"));
            b.line(
                8,
                &format!("uses: actions/cache/restore@{CACHE_ACTION_REF} # {CACHE_ACTION_VERSION}"),
            );
            cache_action_with(b, contract.class, cache, false);
            b.line(
                6,
                &format!("- name: Package immutable {id} restore evidence"),
            );
            b.line(8, &format!("if: {selected}"));
            b.line(8, "shell: bash");
            b.line(8, "env:");
            b.line(
                10,
                &format!("CACHE_HIT: ${{{{ steps.restore-{id}.outputs.cache-hit }}}}"),
            );
            b.run_block(8, &package_cache_script(cache, lane, "restore"));
            b.line(6, &format!("- name: Upload {id} restore evidence"));
            b.line(8, &format!("if: {selected}"));
            b.line(8, &format!("uses: actions/upload-artifact@{UPLOAD_ARTIFACT_REF} # {UPLOAD_ARTIFACT_VERSION}"));
            b.line(8, "with:");
            b.line(
                10,
                &format!("name: proof-restore-{lane}-{id}-${{{{ github.run_id }}}}"),
            );
            b.line(10, &format!("path: .velnor-proof/restore/{lane}/{id}"));
            b.line(10, "if-no-files-found: error");
            b.line(10, "compression-level: 0");
        }
        b.blank();
    }

    b.line(2, "restore_barrier:");
    b.line(4, "name: restore barrier");
    b.line(4, "needs:");
    b.line(6, "- github_restore");
    b.line(6, "- velnor_restore");
    b.line(
        4,
        "if: ${{ inputs.benchmark_campaign != '' || inputs.cache_proof_id != '' }}",
    );
    b.line(4, "runs-on: ubuntu-latest");
    b.line(4, "timeout-minutes: 10");
    b.line(4, "steps:");
    for cache in &declarations {
        let id = cache.id.as_str();
        let selected = format!(
            "${{{{ inputs.cache_proof_id != '' || inputs.benchmark_cache_id == '{id}' }}}}"
        );
        for lane in ["github", "velnor"] {
            b.line(6, &format!("- name: Download {lane} {id} restore evidence"));
            b.line(8, &format!("if: {selected}"));
            b.line(8, &format!("uses: actions/download-artifact@{DOWNLOAD_ARTIFACT_REF} # {DOWNLOAD_ARTIFACT_VERSION}"));
            b.line(8, "with:");
            b.line(
                10,
                &format!("name: proof-restore-{lane}-{id}-${{{{ github.run_id }}}}"),
            );
            b.line(10, &format!("path: .velnor-proof/barrier/{lane}/{id}"));
        }
    }
    b.line(6, "- name: Verify paired restore evidence and temperature");
    b.line(8, "shell: bash");
    b.line(8, "env:");
    b.line(10, "CACHE_TEMPERATURE: ${{ inputs.cache_temperature }}");
    b.line(10, "CACHE_PROOF_ID: ${{ inputs.cache_proof_id }}");
    b.line(10, "BENCHMARK_CACHE_ID: ${{ inputs.benchmark_cache_id }}");
    b.run_block(8, &barrier_script(&declarations));
    b.blank();

    for (job, runner, lane, restore_job) in [
        (
            "github_execute",
            "ubuntu-latest",
            "github",
            "github_restore",
        ),
        (
            "velnor_execute",
            "${{ 'velnor-trusted' }}",
            "velnor",
            "velnor_restore",
        ),
    ] {
        b.line(2, &format!("{job}:"));
        b.line(
            4,
            &format!("name: {lane} execute proof (${{{{ matrix.slot }}}})"),
        );
        b.line(4, "needs:");
        b.line(6, "- restore_barrier");
        b.line(6, &format!("- {restore_job}"));
        b.line(
            4,
            "if: ${{ inputs.benchmark_campaign != '' || inputs.cache_proof_id != '' }}",
        );
        b.line(4, "strategy:");
        b.line(6, "fail-fast: false");
        b.line(6, "matrix:");
        b.line(
            8,
            "slot: ${{ fromJSON(inputs.benchmark_fanout == '8' && '[0,1,2,3,4,5,6,7]' || '[0]') }}",
        );
        b.line(4, &format!("runs-on: {runner}"));
        b.line(4, "timeout-minutes: 45");
        b.line(4, "steps:");
        b.line(6, "- name: Check out repository into fresh workspace");
        b.line(
            8,
            &format!("uses: actions/checkout@{CHECKOUT_REF} # {CHECKOUT_VERSION}"),
        );
        for cache in &declarations {
            let id = cache.id.as_str();
            let selected = format!(
                "${{{{ inputs.cache_proof_id != '' || inputs.benchmark_cache_id == '{id}' }}}}"
            );
            b.line(6, &format!("- name: Download {lane} {id} restore artifact"));
            b.line(8, &format!("if: {selected}"));
            b.line(8, &format!("uses: actions/download-artifact@{DOWNLOAD_ARTIFACT_REF} # {DOWNLOAD_ARTIFACT_VERSION}"));
            b.line(8, "with:");
            b.line(
                10,
                &format!("name: proof-restore-{lane}-{id}-${{{{ github.run_id }}}}"),
            );
            b.line(10, &format!("path: .velnor-proof/execute/{lane}/{id}"));
            b.line(6, &format!("- name: Verify and materialize {lane} {id}"));
            b.line(8, &format!("if: {selected}"));
            b.line(8, "shell: bash");
            b.run_block(8, &materialize_script(id, lane));
        }
        b.line(6, "- name: Set up mise toolchain");
        b.line(
            8,
            &format!("uses: jdx/mise-action@{MISE_ACTION_REF} # {MISE_ACTION_VERSION}"),
        );
        for gate in &contract.gates {
            if gate.applicability == crate::model::Applicability::Both {
                gate_step(b, gate, run_gate);
            }
        }
        b.line(6, "- name: Collect portable proof metrics");
        b.line(8, "shell: bash");
        b.line(8, "env:");
        b.line(10, &format!("PROOF_LANE: {lane}"));
        b.line(10, "PROOF_SLOT: ${{ matrix.slot }}");
        b.line(10, "PROOF_CORRELATION: ${{ needs.restore_barrier.result }}:${{ inputs.benchmark_campaign }}:${{ inputs.cache_proof_id }}");
        b.run_block(8, METRICS_SCRIPT);
        for cache in &declarations {
            let id = cache.id.as_str();
            let selected = format!(
                "${{{{ inputs.cache_proof_id != '' || inputs.benchmark_cache_id == '{id}' }}}}"
            );
            b.line(6, &format!("- name: Package {lane} {id} post-state"));
            b.line(8, &format!("if: {selected}"));
            b.line(8, "shell: bash");
            b.line(8, "env:");
            b.line(10, "CACHE_HIT: post");
            b.run_block(8, &package_cache_script(cache, lane, "post"));
        }
        b.line(6, "- name: Upload execute post-state and metrics");
        b.line(
            8,
            &format!(
                "uses: actions/upload-artifact@{UPLOAD_ARTIFACT_REF} # {UPLOAD_ARTIFACT_VERSION}"
            ),
        );
        b.line(8, "with:");
        b.line(
            10,
            &format!("name: proof-post-{lane}-${{{{ github.run_id }}}}-${{{{ matrix.slot }}}}"),
        );
        b.line(10, "path: |");
        b.line(12, &format!(".velnor-proof/post/{lane}"));
        b.line(12, ".velnor-proof/metrics");
        b.line(10, "if-no-files-found: error");
        b.line(10, "compression-level: 0");
        b.line(6, "- name: Emit execute contract");
        b.line(8, "id: aggregate");
        b.line(8, &format!("uses: {aggregate}"));
        b.blank();
    }

    b.line(2, "cache_publish:");
    b.line(4, "name: sole cache publisher");
    b.line(4, "needs:");
    b.line(6, "- restore_barrier");
    b.line(6, "- github_execute");
    b.line(6, "- velnor_execute");
    b.line(4, "if: ${{ (inputs.cache_proof_id != '' && inputs.cache_temperature == 'cold') || (inputs.benchmark_campaign != '' && inputs.benchmark_cache_mode == 'enabled') }}");
    b.line(4, "runs-on: ubuntu-latest");
    b.line(4, "timeout-minutes: 20");
    b.line(4, "steps:");
    b.line(6, "- name: Check out repository");
    b.line(
        8,
        &format!("uses: actions/checkout@{CHECKOUT_REF} # {CHECKOUT_VERSION}"),
    );
    b.line(6, "- name: Download deterministic GitHub post-state");
    b.line(
        8,
        &format!(
            "uses: actions/download-artifact@{DOWNLOAD_ARTIFACT_REF} # {DOWNLOAD_ARTIFACT_VERSION}"
        ),
    );
    b.line(8, "with:");
    b.line(10, "name: proof-post-github-${{ github.run_id }}-0");
    b.line(10, "path: .velnor-proof/publish");
    for cache in &declarations {
        let id = cache.id.as_str();
        let selected = format!(
            "${{{{ inputs.cache_proof_id != '' || inputs.benchmark_cache_id == '{id}' }}}}"
        );
        b.line(
            6,
            &format!("- name: Materialize deterministic {id} post-state"),
        );
        b.line(8, &format!("if: {selected}"));
        b.line(8, "shell: bash");
        b.run_block(8, &publish_materialize_script(id));
        b.line(6, &format!("- name: Publish {id} exactly once"));
        b.line(8, &format!("if: {selected}"));
        b.line(
            8,
            &format!("uses: actions/cache/save@{CACHE_ACTION_REF} # {CACHE_ACTION_VERSION}"),
        );
        cache_action_with(b, contract.class, cache, false);
    }
    b.blank();

    b.line(2, "cache-proof-contract:");
    b.line(4, "name: cache proof contract");
    b.line(4, "needs:");
    b.line(6, "- github_restore");
    b.line(6, "- velnor_restore");
    b.line(6, "- restore_barrier");
    b.line(6, "- github_execute");
    b.line(6, "- velnor_execute");
    b.line(6, "- cache_publish");
    b.line(
        4,
        "if: ${{ always() && (inputs.benchmark_campaign != '' || inputs.cache_proof_id != '') }}",
    );
    b.line(4, "runs-on: ubuntu-latest");
    b.line(4, "timeout-minutes: 10");
    b.line(4, "outputs:");
    b.line(6, "contract: ${{ steps.contract.outputs.contract }}");
    b.line(4, "steps:");
    b.line(6, "- name: Enforce proof DAG contract");
    b.line(8, "id: contract");
    b.line(8, "shell: bash");
    b.line(8, "env:");
    for name in [
        "GITHUB_RESTORE",
        "VELNOR_RESTORE",
        "RESTORE_BARRIER",
        "GITHUB_EXECUTE",
        "VELNOR_EXECUTE",
        "CACHE_PUBLISH",
    ] {
        let job = name.to_ascii_lowercase();
        b.line(10, &format!("{name}: ${{{{ needs.{job}.result }}}}"));
    }
    b.line(10, "TEMPERATURE: ${{ inputs.cache_temperature }}");
    b.line(10, "BENCHMARK_MODE: ${{ inputs.benchmark_cache_mode }}");
    b.run_block(8, PROOF_CONTRACT_SCRIPT);
    b.blank();
}

fn fixed_roots(cache: &CacheDeclaration) -> String {
    cache
        .paths
        .iter()
        .map(|path| format!("'{path}'"))
        .collect::<Vec<_>>()
        .join(" ")
}

fn clean_cache_script(cache: &CacheDeclaration) -> String {
    format!(
        "set -euo pipefail\nshopt -s globstar nullglob\nfor root in {}; do rm -rf -- \"${{root}}\"; done",
        fixed_roots(cache)
    )
}

fn package_cache_script(cache: &CacheDeclaration, lane: &str, phase: &str) -> String {
    let destination = format!(".velnor-proof/{phase}/{lane}/{}", cache.id);
    format!(
        "set -euo pipefail\nshopt -s globstar nullglob\ndestination='{destination}'\nrm -rf -- \"${{destination}}\"\nmkdir -p -- \"${{destination}}\"\n: > \"${{destination}}/files.list\"\nfor root in {roots}; do\n  if [[ -e \"${{root}}\" ]]; then find \"${{root}}\" -type f -print; fi\ndone | LC_ALL=C sort -u > \"${{destination}}/files.list\"\ntar --sort=name --mtime='@0' --owner=0 --group=0 --numeric-owner -cf \"${{destination}}/cache.tar\" -T \"${{destination}}/files.list\"\nsha256sum \"${{destination}}/files.list\" | cut -d' ' -f1 > \"${{destination}}/manifest.sha256\"\nsha256sum \"${{destination}}/cache.tar\" | cut -d' ' -f1 > \"${{destination}}/archive.sha256\"\nprintf '%s\\n' \"${{CACHE_HIT}}\" > \"${{destination}}/hit\"\nprintf '%s\\n' '{id}' > \"${{destination}}/cache-id\"\nprintf '%s\\n' '{lane}' > \"${{destination}}/lane\"",
        destination = destination,
        roots = fixed_roots(cache),
        id = cache.id,
        lane = lane,
    )
}

fn cache_action_with(
    b: &mut Builder,
    class: RepositoryClass,
    cache: &CacheDeclaration,
    include_restore_prefix: bool,
) {
    b.line(8, "with:");
    b.line(10, "path: |");
    for path in &cache.paths {
        b.line(12, path);
    }
    let globs = cache
        .lock_globs
        .iter()
        .map(|glob| format!("'{glob}'"))
        .collect::<Vec<_>>()
        .join(", ");
    let phase = hex::encode(Sha256::digest(cache.phase.as_bytes()));
    b.line(
        10,
        &format!(
            "key: ci-v${{{{ inputs.cache_generation != '' && inputs.cache_generation || '1' }}}}/{}/{}/${{{{ runner.os }}}}-${{{{ runner.arch }}}}/${{{{ hashFiles('mise.lock', 'mise.toml', 'rust-toolchain.toml') }}}}/${{{{ hashFiles({globs}) }}}}/{phase}",
            class.code(), cache.id
        ),
    );
    if include_restore_prefix && cache.compatible_phase_prefix {
        b.line(10, "restore-keys: |");
        b.line(
            12,
            &format!(
                "ci-v${{{{ inputs.cache_generation != '' && inputs.cache_generation || '1' }}}}/{}/{}/${{{{ runner.os }}}}-${{{{ runner.arch }}}}/${{{{ hashFiles('mise.lock', 'mise.toml', 'rust-toolchain.toml') }}}}/${{{{ hashFiles({globs}) }}}}/",
                class.code(), cache.id
            ),
        );
    }
}

fn barrier_script(declarations: &[&CacheDeclaration]) -> String {
    let mut script = String::from("set -euo pipefail\nselected=0\n");
    for cache in declarations {
        let id = cache.id.as_str();
        script.push_str(&format!(
            "if [[ -n \"${{CACHE_PROOF_ID}}\" || \"${{BENCHMARK_CACHE_ID}}\" == \"{id}\" ]]; then\n  selected=$((selected + 1))\n  github='.velnor-proof/barrier/github/{id}'\n  velnor='.velnor-proof/barrier/velnor/{id}'\n  for root in \"${{github}}\" \"${{velnor}}\"; do\n    test -f \"${{root}}/cache.tar\" -a -f \"${{root}}/archive.sha256\" -a -f \"${{root}}/manifest.sha256\" -a -f \"${{root}}/hit\"\n    test \"$(sha256sum \"${{root}}/cache.tar\" | cut -d' ' -f1)\" = \"$(cat \"${{root}}/archive.sha256\")\"\n  done\n  test \"$(cat \"${{github}}/archive.sha256\")\" = \"$(cat \"${{velnor}}/archive.sha256\")\"\n  if [[ -n \"${{CACHE_PROOF_ID}}\" ]]; then\n    github_hit=\"$(cat \"${{github}}/hit\")\"; velnor_hit=\"$(cat \"${{velnor}}/hit\")\"\n    if [[ \"${{CACHE_TEMPERATURE}}\" == cold ]]; then\n      [[ \"${{github_hit}}\" != true && \"${{velnor_hit}}\" != true ]]\n    else\n      [[ \"${{github_hit}}\" == true && \"${{velnor_hit}}\" == true ]]\n    fi\n  fi\nfi\n"
        ));
    }
    script.push_str(
        "[[ ${selected} -gt 0 ]] || { echo 'zero applicable cache proof work' >&2; exit 1; }\n",
    );
    script
}

fn materialize_script(id: &str, lane: &str) -> String {
    format!(
        "set -euo pipefail\nroot='.velnor-proof/execute/{lane}/{id}'\ntest \"$(sha256sum \"${{root}}/cache.tar\" | cut -d' ' -f1)\" = \"$(cat \"${{root}}/archive.sha256\")\"\ntar -xf \"${{root}}/cache.tar\" -C .\nprintf '%s\\n' '{lane}:{id}:${{{{ matrix.slot }}}}' > \"${{root}}/materialization-id\""
    )
}

fn publish_materialize_script(id: &str) -> String {
    format!(
        "set -euo pipefail\nroot='.velnor-proof/publish/post/github/{id}'\ntest \"$(sha256sum \"${{root}}/cache.tar\" | cut -d' ' -f1)\" = \"$(cat \"${{root}}/archive.sha256\")\"\ntar -xf \"${{root}}/cache.tar\" -C ."
    )
}

const METRICS_SCRIPT: &str = r#"set -euo pipefail
mkdir -p .velnor-proof/metrics
cpu_ms="$(awk '{printf "%d", ($14+$15)*1000/100}' /proc/self/stat 2>/dev/null || printf '0')"
peak_kib="$(awk '/VmHWM:/ {print $2}' /proc/self/status 2>/dev/null || printf '0')"
disk_bytes="$(du -sb . 2>/dev/null | awk '{print $1}' || printf '0')"
psi_cpu="$(tr '\n' ';' < /proc/pressure/cpu 2>/dev/null || true)"
for value in "${cpu_ms}" "${peak_kib}" "${disk_bytes}"; do [[ "${value}" =~ ^[0-9]+$ ]]; done
correlation="$(printf '%s' "${PROOF_CORRELATION}" | tr -cd 'a-zA-Z0-9._:-')"
printf '{"schema":1,"lane":"%s","slot":%s,"cpu_ms":%s,"peak_memory_kib":%s,"disk_bytes":%s,"cache_restore_ms":0,"cache_save_ms":0,"cache_copy_ms":0,"cache_lock_wait_ms":0,"disk_latency_ms":0,"psi_cpu":"%s","cache_result":"proof","cache_bytes":%s,"cache_files":0,"output_digest":"pending","correlation":"%s"}\n' \
  "${PROOF_LANE}" "${PROOF_SLOT}" "${cpu_ms}" "${peak_kib}" "${disk_bytes}" "${psi_cpu}" "${disk_bytes}" "${correlation}" \
  > ".velnor-proof/metrics/${PROOF_LANE}-${PROOF_SLOT}.json"
"#;

/// Fail-closed final truth table for the cache proof DAG.
pub const PROOF_CONTRACT_SCRIPT: &str = r#"set -euo pipefail
for result in "${GITHUB_RESTORE}" "${VELNOR_RESTORE}" "${RESTORE_BARRIER}" "${GITHUB_EXECUTE}" "${VELNOR_EXECUTE}"; do
  [[ "${result}" == success ]] || { echo "proof DAG result ${result}, expected success" >&2; exit 1; }
done
publish_expected=false
[[ "${TEMPERATURE}" == cold || "${BENCHMARK_MODE}" == enabled ]] && publish_expected=true
if ${publish_expected}; then
  [[ "${CACHE_PUBLISH}" == success ]] || { echo "cold/enabled proof publisher did not succeed" >&2; exit 1; }
else
  [[ "${CACHE_PUBLISH}" == skipped ]] || { echo "warm/disabled proof publisher must skip" >&2; exit 1; }
fi
echo 'contract=success' >> "${GITHUB_OUTPUT}"
"#;

fn lane_steps(
    b: &mut Builder,
    contract: &ClassContract,
    caches: &CacheContract,
    lane: Lane,
    run_gate: &str,
    aggregate: &str,
) {
    b.line(6, "- name: Check out repository");
    b.line(
        8,
        &format!("uses: actions/checkout@{CHECKOUT_REF} # {CHECKOUT_VERSION}"),
    );
    if lane == Lane::Velnor {
        for cache in caches
            .declarations()
            .iter()
            .filter(|cache| cache.class == contract.class)
        {
            let id = cache.id.as_str();
            b.line(6, &format!("- name: Capture {id} Velnor cache authority"));
            b.line(8, &format!("id: velnor-authority-{id}"));
            b.line(8, "if: ${{ github.event_name != 'pull_request' && github.event_name != 'merge_group' }}");
            b.line(8, "shell: bash");
            b.line(8, "env:");
            b.line(
                10,
                &format!(
                    "CACHE_ENV_PREFIX: {}",
                    id.replace('-', "_").to_ascii_uppercase()
                ),
            );
            b.run_block(8, VELNOR_AUTHORITY_CAPTURE_SCRIPT);
            b.line(6, &format!("- name: Validate {id} Velnor cache authority"));
            b.line(8, "if: ${{ github.event_name != 'pull_request' && github.event_name != 'merge_group' }}");
            b.line(
                8,
                &format!("uses: {CANONICAL_OWNER}/{ACTIONS_REPO}/actions/cache-contract@{block_sha_placeholder}", block_sha_placeholder = run_gate.rsplit_once('@').map_or("", |(_, sha)| sha)),
            );
            b.line(8, "with:");
            b.line(10, "schema-version: 1");
            b.line(10, &format!("declaration-sha256: ${{{{ steps.velnor-authority-{id}.outputs.declaration_sha256 }}}}"));
            b.line(
                10,
                &format!(
                    "expected-declaration-sha256: {}",
                    caches.declaration_sha256()
                ),
            );
            b.line(
                10,
                &format!("cache-id: ${{{{ steps.velnor-authority-{id}.outputs.cache_id }}}}"),
            );
            b.line(10, &format!("expected-cache-id: {id}"));
            b.line(
                10,
                &format!("scope: ${{{{ steps.velnor-authority-{id}.outputs.scope }}}}"),
            );
            b.line(10, "expected-scope: trusted");
            b.line(
                10,
                &format!("cache-owner: ${{{{ steps.velnor-authority-{id}.outputs.owner }}}}"),
            );
            b.line(10, "expected-cache-owner: ${{ github.repository }}");
            b.line(
                10,
                &format!(
                    "reservation-id: ${{{{ steps.velnor-authority-{id}.outputs.reservation_id }}}}"
                ),
            );
            b.line(
                10,
                &format!(
                    "expected-reservation-id: ${{{{ github.run_id }}}}:${{{{ github.job }}}}:{id}"
                ),
            );
            b.line(10, &format!("required-peak-bytes: {}", cache.peak_bytes));
            b.line(10, &format!("quota-reserved-bytes: ${{{{ steps.velnor-authority-{id}.outputs.reserved_bytes }}}}"));
            b.line(10, &format!("attributed-bytes: ${{{{ steps.velnor-authority-{id}.outputs.attributed_bytes }}}}"));
            b.line(
                10,
                &format!(
                    "cleanup-state: ${{{{ steps.velnor-authority-{id}.outputs.cleanup_state }}}}"
                ),
            );
            b.line(10, &format!("materialization-id: ${{{{ steps.velnor-authority-{id}.outputs.materialization_id }}}}"));
            b.line(10, &format!("expected-materialization-id: ${{{{ github.run_id }}}}-${{{{ github.job }}}}-{id}"));
        }
    }
    let declarations = caches
        .declarations()
        .iter()
        .filter(|cache| cache.class == contract.class)
        .collect::<Vec<_>>();
    b.line(6, "- name: Derive bounded cache keys");
    b.line(8, "id: cache-keys");
    b.line(8, "shell: bash");
    b.line(8, "env:");
    for cache in &declarations {
        let env = cache.id.replace('-', "_").to_ascii_uppercase();
        let globs = cache
            .lock_globs
            .iter()
            .map(|glob| format!("'{glob}'"))
            .collect::<Vec<_>>()
            .join(", ");
        b.line(10, &format!("{env}_TOOLCHAIN: ${{{{ hashFiles('mise.lock', 'mise.toml', 'rust-toolchain.toml') }}}}"));
        b.line(10, &format!("{env}_LOCK: ${{{{ hashFiles({globs}) }}}}"));
        b.line(
            10,
            &format!(
                "{env}_PHASE: {}",
                hex::encode(Sha256::digest(cache.phase.as_bytes()))
            ),
        );
    }
    let mut key_script = String::from("set -euo pipefail\n");
    for cache in &declarations {
        let env = cache.id.replace('-', "_").to_ascii_uppercase();
        let output = cache.id.as_str();
        key_script.push_str(&format!(
            "for value in \"${{{env}_TOOLCHAIN}}\" \"${{{env}_LOCK}}\" \"${{{env}_PHASE}}\"; do [[ \"${{value}}\" =~ ^[0-9a-f]{{64}}$ ]] || {{ echo 'cache key digest missing or invalid' >&2; exit 1; }}; done\nprintf '{output}-toolchain=%s\\n{output}-lock=%s\\n{output}-phase=%s\\n' \"${{{env}_TOOLCHAIN}}\" \"${{{env}_LOCK}}\" \"${{{env}_PHASE}}\" >> \"${{GITHUB_OUTPUT}}\"\n"
        ));
    }
    b.run_block(8, &key_script);
    for cache in declarations {
        if lane == Lane::Velnor {
            cache_step(
                b,
                contract.class,
                cache,
                "restore",
                Some("${{ inputs.lane == 'both' }}"),
            );
            cache_step(
                b,
                contract.class,
                cache,
                "full",
                Some("${{ inputs.lane != 'both' }}"),
            );
        } else {
            cache_step(b, contract.class, cache, "full", None);
        }
    }
    b.line(6, "- name: Set up mise toolchain");
    b.line(
        8,
        &format!("uses: jdx/mise-action@{MISE_ACTION_REF} # {MISE_ACTION_VERSION}"),
    );
    for gate in contract.applicable_gates(lane) {
        if gate.applicability == crate::model::Applicability::Both {
            gate_step(b, gate, run_gate);
        }
    }
    b.line(6, "- name: Emit lane contract");
    b.line(8, "id: aggregate");
    b.line(8, &format!("uses: {aggregate}"));
}

fn cache_step(
    b: &mut Builder,
    class: RepositoryClass,
    cache: &CacheDeclaration,
    mode: &str,
    condition: Option<&str>,
) {
    b.line(
        6,
        &format!(
            "- name: {} {} cache",
            if mode == "restore" {
                "Restore-only"
            } else {
                "Restore and publish"
            },
            cache.id
        ),
    );
    if let Some(condition) = condition {
        b.line(8, &format!("if: {condition}"));
    }
    let path = if mode == "restore" { "/restore" } else { "" };
    b.line(
        8,
        &format!("uses: actions/cache{path}@{CACHE_ACTION_REF} # {CACHE_ACTION_VERSION}"),
    );
    b.line(8, "with:");
    b.line(10, "path: |");
    for path in &cache.paths {
        b.line(12, path);
    }
    let id = cache.id.as_str();
    b.line(
        10,
        &format!(
            "key: ci-v1/{}/{id}/${{{{ runner.os }}}}-${{{{ runner.arch }}}}/${{{{ steps.cache-keys.outputs['{id}-toolchain'] }}}}/${{{{ steps.cache-keys.outputs['{id}-lock'] }}}}/${{{{ steps.cache-keys.outputs['{id}-phase'] }}}}",
            class.code()
        ),
    );
    if mode == "full" && cache.compatible_phase_prefix {
        b.line(10, "restore-keys: |");
        b.line(
            12,
            &format!(
                "ci-v1/{}/{id}/${{{{ runner.os }}}}-${{{{ runner.arch }}}}/${{{{ steps.cache-keys.outputs['{id}-toolchain'] }}}}/${{{{ steps.cache-keys.outputs['{id}-lock'] }}}}/",
                class.code()
            ),
        );
    }
}

fn gate_step(b: &mut Builder, gate: &Gate, run_gate: &str) {
    b.line(6, &format!("- name: {} gate", gate.name));
    b.line(8, &format!("uses: {run_gate}"));
    b.line(8, "with:");
    b.line(10, &format!("name: {}", gate.name));
    b.line(10, &format!("command: {}", gate.command));
}

/// Fail-closed validator for optional recovery, benchmark, and cache-proof operations.
pub const VALIDATE_REQUEST_SCRIPT: &str = r#"set -euo pipefail
fail() { echo "request contract: $*" >&2; exit 1; }
is_id() { [[ "$1" =~ ^[a-z0-9][a-z0-9._:-]{7,127}$ ]]; }
is_declared_cache() { [[ ",${DECLARED_CACHE_IDS}," == *",$1,"* ]]; }
protected_dispatch() {
  [[ "${EVENT_NAME}" == "workflow_dispatch" ]] || fail "operation requires workflow_dispatch"
  [[ "${REF_TYPE}" == "tag" && "${REF_PROTECTED}" == "true" ]] || fail "operation requires protected immutable tag"
  [[ "${HEAD_SHA}" =~ ^[0-9a-f]{40}$ && "${WORKFLOW_SHA}" == "${HEAD_SHA}" ]] || fail "workflow blob does not equal protected tag target"
}

correlation="ordinary"
if [[ -n "${RECOVERY_PROOF_ID}" ]]; then
  [[ "${EVENT_NAME}" == "workflow_dispatch" && "${REF_TYPE}" == "branch" ]] || fail "recovery requires branch dispatch"
  [[ "${HEAD_SHA}" =~ ^[0-9a-f]{40}$ && "${WORKFLOW_SHA}" == "${HEAD_SHA}" ]] || fail "recovery ref is not exact workflow head"
  [[ "${RECOVERY_PROOF_ID}" =~ ^recovery-pr-([1-9][0-9]*)-([0-9a-f]{40})-([a-z0-9][a-z0-9-]{7,63})$ ]] || fail "recovery proof format invalid"
  pr_number="${BASH_REMATCH[1]}"; claimed_sha="${BASH_REMATCH[2]}"
  [[ "${claimed_sha}" == "${HEAD_SHA}" ]] || fail "recovery proof is not bound to dispatched head"
  current_pr_sha="$(gh api "repos/${REPOSITORY}/pulls/${pr_number}" --jq .head.sha)"
  [[ "${current_pr_sha}" == "${HEAD_SHA}" ]] || fail "dispatch ref is not exact current PR head"
  duplicate_count="$(gh api "repos/${REPOSITORY}/actions/runs?event=workflow_dispatch&per_page=100" --paginate --slurp --jq "map(.workflow_runs[]) | map(select(.display_title == \"CI recovery ${RECOVERY_PROOF_ID}\")) | length")"
  [[ "${duplicate_count}" == "1" ]] || fail "duplicate or unknown recovery operation"
  is_id "${RECOVERY_PROOF_ID}" || fail "invalid recovery proof id"
  [[ -z "${BENCHMARK_CAMPAIGN}${CACHE_PROOF_ID}" ]] || fail "recovery cannot combine with another operation"
  correlation="${RECOVERY_PROOF_ID}"
elif [[ -n "${BENCHMARK_CAMPAIGN}" ]]; then
  protected_dispatch
  is_id "${BENCHMARK_CAMPAIGN}" || fail "invalid benchmark campaign"
  [[ "${BENCHMARK_GENERATION}" == "1" ]] || fail "unknown benchmark generation"
  is_declared_cache "${BENCHMARK_CACHE_ID}" || fail "unknown benchmark cache"
  [[ "${BENCHMARK_CACHE_MODE}" =~ ^(normal|enabled|disabled)$ ]] || fail "unknown benchmark cache mode"
  [[ "${BENCHMARK_FANOUT}" =~ ^(1|8)$ ]] || fail "unknown benchmark fanout"
  is_id "${BENCHMARK_WAVE}" || fail "invalid benchmark wave"
  is_id "${BENCHMARK_RESERVATION}" || fail "invalid benchmark reservation"
  [[ -z "${CACHE_PROOF_ID}" ]] || fail "benchmark cannot combine with cache proof"
  correlation="${BENCHMARK_CAMPAIGN}:${BENCHMARK_WAVE}"
elif [[ -n "${CACHE_PROOF_ID}" ]]; then
  protected_dispatch
  is_id "${CACHE_PROOF_ID}" || fail "invalid cache proof id"
  [[ "${CACHE_GENERATION}" =~ ^(1|2)$ ]] || fail "unknown cache generation"
  [[ "${CACHE_TEMPERATURE}" =~ ^(cold|warm)$ ]] || fail "unknown cache temperature"
  correlation="${CACHE_PROOF_ID}:${CACHE_GENERATION}:${CACHE_TEMPERATURE}"
else
  [[ -z "${BENCHMARK_GENERATION}${BENCHMARK_CACHE_ID}${BENCHMARK_CACHE_MODE}${BENCHMARK_FANOUT}${BENCHMARK_WAVE}${BENCHMARK_RESERVATION}${CACHE_GENERATION}${CACHE_TEMPERATURE}" ]] || fail "orphan operation input"
fi
printf 'correlation=%s\n' "${correlation}" >> "${GITHUB_OUTPUT}"
"#;

const VELNOR_AUTHORITY_CAPTURE_SCRIPT: &str = r#"set -euo pipefail
read_field() {
  local name="VELNOR_CACHE_${CACHE_ENV_PREFIX}_$1"
  local value="${!name-}"
  [[ -n "${value}" ]] || { echo "missing Velnor cache authority field ${name}" >&2; exit 1; }
  printf '%s' "${value}"
}
declaration_sha256="$(read_field DECLARATION_SHA256)"
cache_id="$(read_field ID)"
scope="$(read_field SCOPE)"
owner="$(read_field OWNER)"
reservation_id="$(read_field RESERVATION_ID)"
reserved_bytes="$(read_field RESERVED_BYTES)"
attributed_bytes="$(read_field ATTRIBUTED_BYTES)"
cleanup_state="$(read_field CLEANUP_STATE)"
materialization_id="$(read_field MATERIALIZATION_ID)"
{
  printf 'declaration_sha256=%s\n' "${declaration_sha256}"
  printf 'cache_id=%s\n' "${cache_id}"
  printf 'scope=%s\n' "${scope}"
  printf 'owner=%s\n' "${owner}"
  printf 'reservation_id=%s\n' "${reservation_id}"
  printf 'reserved_bytes=%s\n' "${reserved_bytes}"
  printf 'attributed_bytes=%s\n' "${attributed_bytes}"
  printf 'cleanup_state=%s\n' "${cleanup_state}"
  printf 'materialization_id=%s\n' "${materialization_id}"
} >> "${GITHUB_OUTPUT}"
"#;

/// Materialize a consumer file from a committed template by atomically replacing
/// every `@FLEET_SHA@` with `release_sha` and every `@CALVER@` with `calver`.
///
/// Refuses output that still contains either placeholder or that leaves a mixed
/// pin (a `@FLEET_SHA@` without an accompanying replaced `@CALVER@` on the same
/// reference, or vice versa).
///
/// # Errors
///
/// Returns `Err` if the inputs are invalid or any placeholder survives.
pub fn render_consumer(template: &str, release_sha: &str, calver: &str) -> Result<String, String> {
    if !crate::model::is_sha40(release_sha) {
        return Err(format!(
            "release SHA {release_sha:?} is not 40 lowercase hex"
        ));
    }
    if calver.trim().is_empty() {
        return Err("CalVer must be non-empty".to_string());
    }
    if calver.contains('\n') || calver.contains('#') {
        return Err(format!("CalVer {calver:?} contains a forbidden character"));
    }
    let expected_refs = template.matches(FLEET_SHA_PLACEHOLDER).count();
    let out = template
        .replace(FLEET_SHA_PLACEHOLDER, release_sha)
        .replace(CALVER_PLACEHOLDER, calver);
    if out.contains(FLEET_SHA_PLACEHOLDER) || out.contains(CALVER_PLACEHOLDER) {
        return Err("materialized output still contains a placeholder".to_string());
    }
    // Every rendered reference must carry the same replaced SHA and CalVer: the
    // count of pinned refs must match the count of version comments.
    let sha_refs = out.matches(&format!("@{release_sha} # {calver}")).count();
    if sha_refs != expected_refs {
        return Err(format!(
            "mixed pin: expected {expected_refs} coherent @<sha> # <calver> references, found {sha_refs}"
        ));
    }
    Ok(out)
}

const CI_REQUIRED_SCRIPT: &str = r#"set -euo pipefail
# Positive truth table: accept ONLY a recognized owner whose selected call
# succeeded with an explicit contract=success output, and whose two other owner
# calls skipped with empty outputs. No "no failure found" logic; skipped-success
# is never acceptance.
case "${OWNER}" in
  jackin-project)
    sel_result="${JACKIN_PROJECT_RESULT}"; sel_contract="${JACKIN_PROJECT_CONTRACT}"
    a_result="${TAILROCKS_RESULT}"; a_contract="${TAILROCKS_CONTRACT}"
    b_result="${CHAINARGOS_RESULT}"; b_contract="${CHAINARGOS_CONTRACT}"
    ;;
  tailrocks)
    sel_result="${TAILROCKS_RESULT}"; sel_contract="${TAILROCKS_CONTRACT}"
    a_result="${JACKIN_PROJECT_RESULT}"; a_contract="${JACKIN_PROJECT_CONTRACT}"
    b_result="${CHAINARGOS_RESULT}"; b_contract="${CHAINARGOS_CONTRACT}"
    ;;
  ChainArgos)
    sel_result="${CHAINARGOS_RESULT}"; sel_contract="${CHAINARGOS_CONTRACT}"
    a_result="${JACKIN_PROJECT_RESULT}"; a_contract="${JACKIN_PROJECT_CONTRACT}"
    b_result="${TAILROCKS_RESULT}"; b_contract="${TAILROCKS_CONTRACT}"
    ;;
  *)
    echo "ci-required: unrecognized owner '${OWNER}'" >&2
    exit 1
    ;;
esac
if [ "${sel_result}" != "success" ]; then
  echo "ci-required: selected owner result is '${sel_result}', expected 'success'" >&2
  exit 1
fi
if [ "${sel_contract}" != "success" ]; then
  echo "ci-required: selected owner contract is '${sel_contract}', expected 'success'" >&2
  exit 1
fi
if [ "${a_result}" != "skipped" ] || [ "${b_result}" != "skipped" ]; then
  echo "ci-required: a non-selected owner ran (results '${a_result}', '${b_result}'), expected both 'skipped'" >&2
  exit 1
fi
if [ -n "${a_contract}" ] || [ -n "${b_contract}" ]; then
  echo "ci-required: a non-selected owner produced a contract output, expected empty" >&2
  exit 1
fi
echo "ci-required: fleet contract satisfied for owner '${OWNER}'""#;

const CONTRACT_VERDICT_SCRIPT: &str = r#"set -euo pipefail
# Positive per-lane truth table: emit contract=success ONLY when every selected
# lane succeeded with contract=success and every non-selected lane is skipped with
# an empty output. A failed, unavailable, or skipped selected lane is never
# credited, and one lane never substitutes for the other.
if [ "${OPERATION}" != ordinary ]; then
  if [ "${CACHE_PROOF_RESULT}" != success ] || [ "${CACHE_PROOF_CONTRACT}" != success ]; then
    echo "contract: ${OPERATION} proof DAG did not pass" >&2
    exit 1
  fi
  if [ "${VELNOR_RESULT}" != skipped ] || [ "${GITHUB_RESULT}" != skipped ] || [ -n "${VELNOR_CONTRACT}${GITHUB_CONTRACT}" ]; then
    echo "contract: ordinary lane jobs ran during ${OPERATION}" >&2
    exit 1
  fi
else
case "${LANE}" in
  velnor)
    if [ "${VELNOR_RESULT}" != "success" ] || [ "${VELNOR_CONTRACT}" != "success" ]; then
      echo "contract: velnor lane did not pass (result '${VELNOR_RESULT}', contract '${VELNOR_CONTRACT}')" >&2
      exit 1
    fi
    if [ "${GITHUB_RESULT}" != "skipped" ] || [ -n "${GITHUB_CONTRACT}" ]; then
      echo "contract: github lane must be skipped for lane=velnor (result '${GITHUB_RESULT}')" >&2
      exit 1
    fi
    ;;
  github)
    if [ "${GITHUB_RESULT}" != "success" ] || [ "${GITHUB_CONTRACT}" != "success" ]; then
      echo "contract: github lane did not pass (result '${GITHUB_RESULT}', contract '${GITHUB_CONTRACT}')" >&2
      exit 1
    fi
    if [ "${VELNOR_RESULT}" != "skipped" ] || [ -n "${VELNOR_CONTRACT}" ]; then
      echo "contract: velnor lane must be skipped for lane=github (result '${VELNOR_RESULT}')" >&2
      exit 1
    fi
    ;;
  both)
    if [ "${VELNOR_RESULT}" != "success" ] || [ "${VELNOR_CONTRACT}" != "success" ]; then
      echo "contract: velnor lane did not pass (result '${VELNOR_RESULT}', contract '${VELNOR_CONTRACT}')" >&2
      exit 1
    fi
    if [ "${GITHUB_RESULT}" != "success" ] || [ "${GITHUB_CONTRACT}" != "success" ]; then
      echo "contract: github lane did not pass (result '${GITHUB_RESULT}', contract '${GITHUB_CONTRACT}')" >&2
      exit 1
    fi
    ;;
  *)
    echo "contract: unrecognized lane '${LANE}'" >&2
    exit 1
    ;;
esac
  if [ "${CACHE_PROOF_RESULT}" != skipped ] || [ -n "${CACHE_PROOF_CONTRACT}" ]; then
    echo "contract: proof DAG ran during ordinary execution" >&2
    exit 1
  fi
fi
if [ "${PLATFORM_REQUIRED}" = "true" ]; then
  if [ "${PLATFORM_RESULT}" != "success" ] || [ "${PLATFORM_CONTRACT}" != "success" ]; then
    echo "contract: required GitHub platform lane did not pass" >&2
    exit 1
  fi
elif [ "${PLATFORM_RESULT}" != "skipped" ] || [ -n "${PLATFORM_CONTRACT}" ]; then
  echo "contract: unexpected GitHub platform lane execution" >&2
  exit 1
fi
echo "contract=success" >> "${GITHUB_OUTPUT}"
echo "contract: lane '${LANE}' passed""#;
